/* eslint-disable */
/**
 * Generated by Convex. Run `npx convex dev` to regenerate this file.
 * This is a placeholder – real types are generated by the Convex CLI.
 */
import type { ApiFromModules } from "convex/server";
import type * as auth from "../auth.js";
import type * as handouts from "../handouts.js";
import type * as sessions from "../sessions.js";
import type * as seed from "../seed.js";
import type * as viewers from "../viewers.js";
import type * as init from "../init.js";

export type Mounts = {
  auth: typeof auth;
  handouts: typeof handouts;
  sessions: typeof sessions;
  seed: typeof seed;
  viewers: typeof viewers;
  init: typeof init;
};

declare const fullApi: ApiFromModules<Mounts>;
export declare const api: typeof fullApi;
export declare const internal: typeof fullApi;
