/* eslint-disable */
/**
 * Generated by Convex. Run `npx convex dev` to regenerate.
 */
import type { GenericActionCtx, GenericMutationCtx, GenericQueryCtx } from "convex/server";
import type { DataModel } from "./dataModel.js";

export type QueryCtx = GenericQueryCtx<DataModel>;
export type MutationCtx = GenericMutationCtx<DataModel>;
export type ActionCtx = GenericActionCtx<DataModel>;

export declare const query: import("convex/server").RegisteredQuery<"public", any, any>;
export declare const mutation: import("convex/server").RegisteredMutation<"public", any, any>;
export declare const action: import("convex/server").RegisteredAction<"public", any, any>;
export declare const internalQuery: import("convex/server").RegisteredQuery<"internal", any, any>;
export declare const internalMutation: import("convex/server").RegisteredMutation<"internal", any, any>;
export declare const internalAction: import("convex/server").RegisteredAction<"internal", any, any>;
